Repository CodeQuestic/OpenPrep, pull requests merged in 2024-10, with the labels that each got.

#29 [Docs] (React) : React Hooks Using Astro Components
  src/content/docs/react/codes/hooksCode/CustomHook/CounterComponent.txt
  src/content/docs/react/codes/hooksCode/CustomHook/Usage.txt
  src/content/docs/react/codes/hooksCode/Others/Cleanup.txt
  src/content/docs/react/codes/hooksCode/Others/UsageOne.txt
  src/content/docs/react/codes/hooksCode/Others/UsageTwo.txt
  src/content/docs/react/codes/hooksCode/useCallBack/Counter.txt
  src/content/docs/react/codes/hooksCode/useCallBack/Usage.txt
  src/content/docs/react/codes/hooksCode/useContext/App.txt
  src/content/docs/react/codes/hooksCode/useContext/Usage.txt
  src/content/docs/react/codes/hooksCode/useEffect/DataFetchingComponent.txt
  src/content/docs/react/codes/hooksCode/useEffect/Usage.txt
  src/content/docs/react/codes/hooksCode/useMemo/App.txt
  src/content/docs/react/codes/hooksCode/useMemo/ExpensiveComponent.txt
  src/content/docs/react/codes/hooksCode/useMemo/Usage.txt
  src/content/docs/react/codes/hooksCode/useReducer/Counter.txt
  src/content/docs/react/codes/hooksCode/useReducer/Usage.txt
  src/content/docs/react/codes/hooksCode/useRef/FocusInput.txt
  src/content/docs/react/codes/hooksCode/useRef/Usage.txt
  src/content/docs/react/codes/hooksCode/useState/Counter.txt
  src/content/docs/react/codes/hooksCode/useState/Usage.txt
  src/content/docs/react/hooks.mdx
Labels: status: waiting update, guidelines followed

#30 [docs](Mongo DB): Replication and Sharding in MongoDB
  package-lock.json
  package.json
  src/content/docs/mongodb/replication-and-sharding.mdx
Labels: status: waiting update, guidelines followed

#32 [docs](Node): Updated Node theory concept
  src/content/docs/node/codes/introductionCode/introduction.txt
  src/content/docs/node/introduction.mdx
Labels: status: waiting update, guidelines followed

#39 [docs](React): Added documentation for forms in React, covering controlled/uncontrolled components, validation, and submissions.
  src/content/docs/react/codes/forms/controlled/ControlledInput.txt
  src/content/docs/react/codes/forms/controlled/ControlledSelect.txt
  src/content/docs/react/codes/forms/controlled/ControlledTextarea.txt
  src/content/docs/react/codes/forms/validation/Formik.txt
  src/content/docs/react/codes/forms/validation/Hooks.txt
  src/content/docs/react/forms.mdx
Labels: guidelines followed, status: waiting review

#40 [docs](MongoDB): Schema Design Best Practices
  src/content/docs/mongodb/schema-design-best-practices.mdx
Labels: guidelines followed, status: waiting review

#42 [docs](Node): Added Node stream
  src/content/docs/node/streams.mdx
Labels: guidelines followed, status: waiting review

#43 [docs](React): Added Handling User Events (onClick, onChange, etc.) Event Binding and Event Handlers Synthetic Events in React Passing Arguments to Event Handlers
  src/content/docs/react/codes/eventHandlingCode/arguments/bind.txt
  src/content/docs/react/codes/eventHandlingCode/arguments/dependencies.txt
  src/content/docs/react/codes/eventHandlingCode/commonhandlers/focusblur.txt
  src/content/docs/react/codes/eventHandlingCode/commonhandlers/keyevents.txt
  src/content/docs/react/codes/eventHandlingCode/commonhandlers/mouse.txt
  src/content/docs/react/codes/eventHandlingCode/commonhandlers/onchange.txt
  src/content/docs/react/codes/eventHandlingCode/commonhandlers/onclick.txt
  src/content/docs/react/codes/eventHandlingCode/commonhandlers/onscroll.txt
  src/content/docs/react/codes/eventHandlingCode/commonhandlers/onsubmit.txt
  src/content/docs/react/codes/eventHandlingCode/handling/classcomponents.txt
  src/content/docs/react/codes/eventHandlingCode/handling/funccomponents.txt
  src/content/docs/react/codes/eventHandlingCode/syntheticevents/exm.txt
  src/content/docs/react/codes/eventHandlingCode/syntheticevents/pooling.txt
  src/content/docs/react/event-handling.mdx
Labels: hacktoberfest-accepted, guidelines followed, status: accepted
